os:
  - linux
  - osx

# This makes us use Ubuntu 14 instead of 12
dist: trusty

# Notes:
# - Travis uses cmake 3.0.2 on OS X; we need 3.1 or newer (thanks tbodt)

language: csharp
mono:
  - latest

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libgtk-3-dev libssl-dev libunwind8 zlib1g libicu-dev libcurl4-openssl-dev gettext gcc -y || sudo apt-cache search libgtk3; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl && ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/ && ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi 
script:
  - ./build.sh package

addons:
  artifacts:
    s3_region: "us-east-1"
    paths:
    - $(ls ./artifacts/build/*.nupkg | tr "\n" ":")

