os: Visual Studio 2015
version: Build {build}

configuration:
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - cmd: build.cmd package

artifacts:
  - path: artifacts/build/*.nupkg
    name: libui build package - Windows

